meta_product_name: «GYMATE»
meta_title: "GYMATE - Restez en forme et connectés. GYMATE - Votre compagnon de Sport !"
meta_description: "GYMATE est une application web qui va te permettre de trouver un partenaire en fonction du sport choisi, de tes objectifs et de ta localisation."
meta_image: "favicon-32x32.png"
